name: Python application

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint coverage pytest "poetry==1.7.1" pyaml
        poetry install 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: see content
      run: ls -la
    - name: Lint with pylint
      run: pylint pyargwriter --fail-under 7.5
      continue-on-error: true
    - name: Test with pytest
      run: |
        python -m coverage run -m pytest
    - name: pytest coverage
      run:
        python -m coverage report > documentation/coverage_report.md


